### ISSUE TITLE
Update repository for hacktoberfest 2020

### ISSUE THREAD

**Issue by arc9693** [lugnitdgp/Hactoberfest-Hack-Day-2019#211]
- [x] Update README.md
- [x] Create CONTRIBUTING.md
- [x] Create/Update Countdown/landing page

**Comment by arc9693** [comment]
@YASHMAROO Can you make the other required updates please?

**Comment by YASHMAROO** [comment]
> @YASHMAROO Can you make the other required updates please?

@arc9693I will make the required updates .

**Comment by arc9693** [comment]
Closing issue due to completion. Related PRs: #216 #212
