### ISSUE TITLE
Implementing Caching of github API data

### ISSUE THREAD

**Issue by arc9693** [lugnitdgp/Hactoberfest-Hack-Day-2019#214]
Right now the website loading takes a lot of time due to repetitive API calls and it also crosses the rate limit.
Potential solutions: 

1. Using local storage - https://www.w3schools.com/jsref/prop_win_localstorage.asp
2. Moving the code to node js and implementing the cache

**Comment by arc9693** [comment]
@Abha2001 Take a look.

**Comment by Abha2001** [comment]
ok i will work on it
