### ISSUE TITLE
Click Here button not working

### ISSUE THREAD

**Issue by Abha2001** [lugnitdgp/Hactoberfest-Hack-Day-2019#283]
The click here button on the home page is currently doing nothing upon clicking. It should scroll up the page so that the ninja cards appear from the top of the page.

**Comment by faisaljamil25** [comment]
I would like to do this.

**Comment by Abha2001** [comment]
Sure! Go ahead and give it a try!

**Comment by MuditJain5** [comment]
I have made PR resolving the issue

**Comment by shruticode81** [comment]
hey! Abha2001 I would love to contribute

**Comment by shruticode81** [comment]
we have to make changes in index.html file?

**Comment by Abha2001** [comment]
This issue has been resolved and hence is being closed. Those willing to contribute, please have a look at the other issues.
